export default {
  login: "abelmiraval",
  id: 35229830,
  node_id: "MDQ6VXNlcjM1MjI5ODMw",
  avatar_url: "https://avatars.githubusercontent.com/u/35229830?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/abelmiraval",
  html_url: "https://github.com/abelmiraval",
  followers_url: "https://api.github.com/users/abelmiraval/followers",
  following_url:
    "https://api.github.com/users/abelmiraval/following{/other_user}",
  gists_url: "https://api.github.com/users/abelmiraval/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/abelmiraval/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/abelmiraval/subscriptions",
  organizations_url: "https://api.github.com/users/abelmiraval/orgs",
  repos_url: "https://api.github.com/users/abelmiraval/repos",
  events_url: "https://api.github.com/users/abelmiraval/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/abelmiraval/received_events",
  type: "User",
  site_admin: false,
  name: "Abel Miraval",
  company: null,
  blog: "https://abelmiraval.com",
  location: "Peru",
  email: null,
  hireable: null,
  bio: null,
  twitter_username: "abelmiraval",
  public_repos: 96,
  public_gists: 7,
  followers: 13,
  following: 211,
  created_at: "2018-01-08T15:37:02Z",
  updated_at: "2023-02-11T18:12:06Z",
};
